### ISSUE TITLE
Remove odoo.com Bindings is not working with Odoo 12.0 Community 

### ISSUE THREAD

**Issue by horacecar** [OCA/server-brand#17]
Remove odoo.com Bindings is not working with Odoo 12.0 Community 
![222](https://user-images.githubusercontent.com/44496483/70352270-bbf09c80-18a5-11ea-9c3a-875c3364b130.png)
![111](https://user-images.githubusercontent.com/44496483/70352271-bbf09c80-18a5-11ea-817c-488bed55c078.png)

**Comment by pedrobaeza** [comment]
Why not?

**Comment by horacecar** [comment]
@pedrobaeza  not sure, but i am thinking about may be the version?? the image i pull out from dockerhub is (odoo 12.0-20191106)  , or do i neet to setup anything or Parameters to make it work? Or it will work after i installed? i already try to reboot the docker container and clear the cookies, but still not working

**Comment by pedrobaeza** [comment]
What I see is that you don't have correctly the addons path or similar, as the icon is not shown. Any way, it's not a problem of the module itself, so closing.

**Comment by horacecar** [comment]
![333](https://user-images.githubusercontent.com/44496483/70353635-c82a2900-18a8-11ea-8163-18c8471ac04a.png)
@pedrobaeza  I am sorry, but i am sure i installed it correctly..... because other module is working fine with that path.....

**Comment by horacecar** [comment]
Is it possible in the latest version of November 06 of (odoo v12.0-20191106) changed something ?

**Comment by pedrobaeza** [comment]
I don't think so.
