### ISSUE TITLE
What is it for?

### ISSUE THREAD

**Issue by chrizzTs** [OCA/server-brand#5]
Hi all,

I am still struggeling a little bit to understand what this module ist for.
What I understood ist following:
1) It removes filed maked as "Enterprise feature" from settings views

I do not understand the part about the bindings to Odoo.com. Could you please explain what it does or how and if Odoo Coomunity is connecting to Odoo.com in standard?

Thanks in advance!

**Comment by pedrobaeza** [comment]
Which module?

**Comment by emanjuGbr** [comment]
Sorry I meant this whole repository.
I think what I understood was module:
res_config_settings_enterprise_remove.

What I do not understand is module: disable_odoo_online

Thanks in advance!

**Comment by pedrobaeza** [comment]
Please read the description of the module or ask in the forums/mailing lists, as this issue tracker is only for reporting issues/bugs with the modules.
