### ISSUE TITLE
[13] remove_odoo_enterprise - AttributeError: 'int' object has no attribute 'filtered'

### ISSUE THREAD

**Issue by sergioeix** [OCA/server-brand#52]
## Module
remove_odoo_enterprise 

## Describe the bug
When you try to create a new journal an error is shown

## To Reproduce
**Affected versions**: 13
With the last source update this error is shown when you try to create a new journal

1. Go to invoicing settings journals
2. Create a new journal type misc and set a sequence code
3. try to save

![image](https://user-images.githubusercontent.com/62206774/164735596-376a61e5-b877-45ec-bf02-8e874be2011a.png)

**Expected behavior**
Create the new journal as normal

**Additional context**
When module is uninstalled you can create the journal as normal

**Comment by jguenat** [comment]
Hi,
I had the same issue, the search method can return an integer if the count parameter is set to true. This will create the above mentioned traceback in the following code :

https://github.com/OCA/server-brand/blob/07c308af21cb1ef0f9e6df2e14cffc04591b16ab/remove_odoo_enterprise/models/base.py#L10-L15

I'll create a PR to fix it.

**Comment by jguenat** [comment]
@sergioeix Can you review it?

Hello @dreispt 
What is the OCA way to port a fix to other branches (14 and 15 in this case) ?
Thanks!

**Comment by sergioeix** [comment]
@jguenat now is working as expected
