### ISSUE TITLE
[15.0][Bug] AttributeError: module 'odoo.api' has no attribute 'multi'

### ISSUE THREAD

**Issue by ghost** [OCA/server-brand#56]
## Module
Remove odoo.com Bindings

## Describe the bug
When trying to install Odoo emits a stack trace with the following Information.
`RPC_ERROR`
`Odoo Server Error`
`Traceback (most recent call last):`
`  File "/home/odoo/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch`
`    result = request.dispatch()`
`  File "/home/odoo/odoo/odoo/http.py", line 687, in dispatch`
`    result = self._call_function(**self.params)`
`  File "/home/odoo/odoo/odoo/http.py", line 359, in _call_function`
`    return checked_call(self.db, *args, **kwargs)`
`  File "/home/odoo/odoo/odoo/service/model.py", line 94, in wrapper`
`    return f(dbname, *args, **kwargs)`
`  File "/home/odoo/odoo/odoo/http.py", line 348, in checked_call`
`    result = self.endpoint(*a, **kw)`
`  File "/home/odoo/odoo/odoo/http.py", line 916, in __call__`
`    return self.method(*args, **kw)`
`  File "/home/odoo/odoo/odoo/http.py", line 535, in response_wrap`
`    response = f(*args, **kw)`
`  File "/home/odoo/odoo/addons/web/controllers/main.py", line 1351, in call_button`
`    action = self._call_kw(model, method, args, kwargs)`
`  File "/home/odoo/odoo/addons/web/controllers/main.py", line 1339, in _call_kw`
`    return call_kw(request.env[model], method, args, kwargs)`
`  File "/home/odoo/odoo/odoo/api.py", line 464, in call_kw`
`    result = _call_kw_multi(method, model, args, kwargs)`
`  File "/home/odoo/odoo/odoo/api.py", line 451, in _call_kw_multi`
`    result = method(recs, *args, **kwargs)`
`  File "<decorator-gen-74>", line 2, in button_immediate_install`
`  File "/home/odoo/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log`
`    return method(self, *args, **kwargs)`
`  File "/home/odoo/odoo/odoo/addons/base/models/ir_module.py", line 483, in button_immediate_install`
`    return self._button_immediate_function(type(self).button_install)`
`  File "/home/odoo/odoo/odoo/addons/base/models/ir_module.py", line 600, in _button_immediate_function`
`    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)`
`  File "/home/odoo/odoo/odoo/modules/registry.py", line 87, in new`
`    odoo.modules.load_modules(registry, force_demo, status, update_module)`
`  File "/home/odoo/odoo/odoo/modules/loading.py", line 474, in load_modules`
`    processed_modules += load_marked_modules(cr, graph,`
`  File "/home/odoo/odoo/odoo/modules/loading.py", line 363, in load_marked_modules`
`    loaded, processed = load_module_graph(`
`  File "/home/odoo/odoo/odoo/modules/loading.py", line 179, in load_module_graph`
`    load_openerp_module(package.name)`
`  File "/home/odoo/odoo/odoo/modules/module.py", line 396, in load_openerp_module`
`    __import__('odoo.addons.' + module_name)`
`  File "/home/odoo/addons/disable_odoo_online/__init__.py", line 4, in <module>`
`    from . import models`
`  File "/home/odoo/addons/disable_odoo_online/models/__init__.py", line 1, in <module>`
`    from . import publisher_warranty_contract`
`  File "/home/odoo/addons/disable_odoo_online/models/publisher_warranty_contract.py", line 8, in <module>`
`    class PublisherWarrantyContract(models.AbstractModel):`
`  File "/home/odoo/addons/disable_odoo_online/models/publisher_warranty_contract.py", line 11, in PublisherWarrantyContract`
`    @api.multi`
`Exception`
``
`The above exception was the direct cause of the following exception:`
``
`Traceback (most recent call last):`
`  File "/home/odoo/odoo/odoo/http.py", line 643, in _handle_exception`
`    return super(JsonRequest, self)._handle_exception(exception)`
`  File "/home/odoo/odoo/odoo/http.py", line 301, in _handle_exception`
`    raise exception.with_traceback(None) from new_cause`
`AttributeError: module 'odoo.api' has no attribute 'multi'`

## To Reproduce
**Affected versions**:

1. Fresh Odoo 15 Source Install
2. Search Remove in Apps
3. Client install for Remove odoo.com Bindings

**Expected behavior**
Install and remove odoo bindings from locations such as the user menu.

**Additional context**
Fedora 36 VPS
Python 3.10.4
PostgreSQL Server 14 (Different VPS)

**Comment by vincent-hatakeyama** [comment]
You are not using the correct version of the module. The code referenced by ` File "/home/odoo/addons/disable_odoo_online/models/publisher_warranty_contract.py", line 11, in PublisherWarrantyContract' indicates `@api.multi` but that code is not present in https://github.com/OCA/server-brand/blob/15.0/disable_odoo_online/models/publisher_warranty_contract.py#L11
