### ISSUE TITLE
disable_odoo_online Working partially

### ISSUE THREAD

**Issue by Ahmed4120** [OCA/server-brand#60]
I installed disable_odoo_online on a fresh Odoo v15 successfully , from https://apps.odoo.com/apps/modules/15.0/disable_odoo_online   (disable_odoo_online-15.0.1.0.0.zip) 

**The result is:** 
- apps and updates menu items in settings are hidden inside Technical Parameters (Successfully) 
- documentation, support and odoo.com account are removed from user menu (Not Working)

I expected that user memu will be free of Odoo.com link but it doesn't happen.

**Comment by pedrobaeza** [comment]
Right now is not in the scope of the module. You can contribute with such feature.
