### ISSUE TITLE
[14][portal_odoo_debranding] Login screen shows "powered by odoo"

### ISSUE THREAD

**Issue by ghost** [OCA/server-brand#70]
Hi all,

We encounter an issue with the login in this module. When getting into the login page, it shows underneath the login "powered by odoo" This module suppose to remove all the odoo branding in the portal, but this part is missing.

Thank you!

@moduon MT-2218
![imagen](https://user-images.githubusercontent.com/106727438/219637988-3fa83c4e-f892-4451-bd77-9950c22a4938.png)

**Comment by ghost** [comment]
ping @eLBati @ivantodorovich

**Comment by ivantodorovich** [comment]
Hello! Thanks for reporting it! Indeed, it seems that's missing
I'll try to take care of this asap. Alternatively, a PR with a fix is most welcomed 🙏🏻

**Comment by ghost** [comment]
Hi,
Thanks for answering back!
Sorry, not a programmer, just functional, if not I would be more than happy to send the PR!
Thanks in advance

**Comment by madatr** [comment]
Hi! Any update on this?
