### ISSUE TITLE
Remove Odoo branding from mail template

### ISSUE THREAD

**Issue by arnaudlayec** [OCA/server-brand#82]
module: disable_odoo_online
version: 16.0

Hello,
This is my 1st contribution in general both through Github and OCA, so I'm sorry if this could not be the right place for this message.
I was thinking this module could help removing the "Powered by Odoo" at the bottom of email default template.
A way to do it seems to inherit from **mail.mail_notification_layout** in `mode=extension`, like below.

Feel free to redirect me anywhere if needed.
Kind regards

![image](https://github.com/OCA/server-brand/assets/36078845/aeae7017-ca50-4aca-bea6-d8978c006d13)

**Comment by etobella** [comment]
Sure! Can you add a PR  with the change?

**Comment by kikopeiro** [comment]
https://github.com/OCA/social/tree/16.0/mail_debrand

**Comment by arnaudlayec** [comment]
Thanks kikopeiro, missed this one. So it closes the issue!
