### ISSUE TITLE
[16.0, 17.0] remove_odoo_enterprise: debranding res.config.settings bug

### ISSUE THREAD

**Issue by tarteo** [OCA/server-brand#90]
When accessing the settings (res.config.settings) from Sales, all enterprise options are visible. However, when accessed through Invoicing, these options are not displayed, which is the expected behavior

From sales:
![image](https://github.com/user-attachments/assets/936fb8a0-0794-4d34-93d7-eec2f1c3f480)

From invoicing:
![image](https://github.com/user-attachments/assets/528716cb-ad62-41f1-92eb-15e9a7f50af1)

## Module
remove_odoo_enterprise

## To Reproduce
**16.0, 17.0**:

1. Go to Sales > Configuration > Settings
2. Enterprise options are there
3. Go to Invoicing > Configuration > Settings
4. Enterprise options aren't there

**Additional context**
You can see it on runboat

**Comment by tarteo** [comment]
It's the same for the lunch module. It happens because the action is directly referencing the inherited view. 

https://github.com/odoo/odoo/blob/04d199187e2d698f6adfcca34121454ed0a188b6/addons/lunch/views/res_config_settings.xml#L56

https://github.com/OCA/server-brand/blob/12c1e61d0d04d380bbb53ff3c117c4f7fe80b0b0/remove_odoo_enterprise/models/res_config_settings.py#L19

**Comment by remi-filament** [comment]
By the way, the problem is also present in v15 (I checked previous versions as well, and it does not seem present in 12, 13, 14)
